const colleges = [
  {
    id: 1,
    name: "Jawaharlal Nehru Rajkeeya  Mahavidyalaya (Id: C-6498)",
    location: "Nicobars",
    state: "Andaman and Nicobar Islands",
    district: "Nicobars",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1967,
    medium: ["English"],
    type: "No",
  },
  {
    id: 2,
    name: "Regional Medical Research Institute (I.C.M.R.) (Id: C-6575)",
    location: "Nicobars",
    state: "Andaman and Nicobar Islands",
    district: "Nicobars",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1983,
    medium: ["English"],
    type: "Medical-Others",
  },
  {
    id: 3,
    name: "Tagore Government College of Education (Id: C-6574)",
    location: "Nicobars",
    state: "Andaman and Nicobar Islands",
    district: "Nicobars",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1981,
    medium: ["English"],
    type: "Education/Teacher Education",
  },
  {
    id: 4,
    name: "Zoological Survey of India (Id: C-6560)",
    location: "Nicobars",
    state: "Andaman and Nicobar Islands",
    district: "Nicobars",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1977,
    medium: ["English"],
    type: "Science",
  },
  {
    id: 5,
    name: "Mahatma Gandhi Govt. College (Id: C-6547)",
    location: "North and Middle Andaman",
    state: "Andaman and Nicobar Islands",
    district: "North and Middle Andaman",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1990,
    medium: ["English"],
    type: "No",
  },
  {
    id: 6,
    name: "Andaman and Nicobar inslands Institute of medical sciences (Id: C-60180)",
    location: "South Andamans",
    state: "Andaman and Nicobar Islands",
    district: "South Andamans",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 2015,
    medium: ["English"],
    type: "Medical-Allopathy",
  },
  {
    id: 7,
    name: "ANDAMAN COLLEGE (ANCOL) (Id: C-50934)",
    location: "South Andamans",
    state: "Andaman and Nicobar Islands",
    district: "South Andamans",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 2014,
    medium: ["English"],
    type: "No",
  },
  {
    id: 8,
    name: "ANDAMAN LAW COLLEGE (Id: C-63976)",
    location: "South Andamans",
    state: "Andaman and Nicobar Islands",
    district: "South Andamans",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 2016,
    medium: ["English"],
    type: "Law",
  },
  {
    id: 9,
    name: "Dr.B.R. Ambedkar Institute of Technology (Id: C-6528)",
    location: "South Andamans",
    state: "Andaman and Nicobar Islands",
    district: "South Andamans",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 1984,
    medium: ["English"],
    type: "No",
  },
  {
    id: 10,
    name: "College of Agricultural Engineering, Madakasira (Id: C-26381)",
    location: "Anantapur",
    state: "Andhra Pradesh",
    district: "Anantapur",
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "B.Sc. Biology"],
    fees: { general: 6000, sc_st: 3000, obc: 4000 },
    cutoffs: { general: 85, sc_st: 75, obc: 80 },
    facilities: ["Library", "Hostel", "Sports Ground"],
    rating: 4.0,
    students: 1500,
    established: 2008,
    medium: ["English"],
    type: "Engineering & Technology",
  },
];

export default colleges;
