import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/*
          Some browser extensions (notably Grammarly) inject attributes onto
          the <body> element at runtime (for example: data-gr-ext-installed,
          data-new-gr-c-s-check-loaded). That can cause React hydration
          mismatches because the server-rendered HTML doesn't include them.

          This small inline script removes those known attributes early during
          parsing so the DOM the client-side React sees matches the server
          markup and prevents hydration errors in development.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `;(function(){try{const b=document && document.body;if(b){b.removeAttribute('data-gr-ext-installed');b.removeAttribute('data-new-gr-c-s-check-loaded');}}catch(e){} })()`
          }}
        />
        {children}
      </body>
    </html>
  );
}
